# Generated by Django 6.0.4 on 2026-04-20 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GPPractices',
            fields=[
                ('practice_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('list_size', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('postcode', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('health_board', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GPDetails',
            fields=[
                ('medical_council_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=100)),
                ('forename', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=10, null=True)),
                ('surname', models.CharField(max_length=100)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gp', to='catalog.gppractices')),
            ],
            options={
                'ordering': ['surname', 'forename'],
            },
        ),
        migrations.CreateModel(
            name='GPPopulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
                ('ages00to04', models.IntegerField(default=0)),
                ('ages05to09', models.IntegerField(default=0)),
                ('ages10to14', models.IntegerField(default=0)),
                ('ages15to19', models.IntegerField(default=0)),
                ('ages20to24', models.IntegerField(default=0)),
                ('ages25to29', models.IntegerField(default=0)),
                ('ages30to34', models.IntegerField(default=0)),
                ('ages35to39', models.IntegerField(default=0)),
                ('ages40to44', models.IntegerField(default=0)),
                ('ages45to49', models.IntegerField(default=0)),
                ('ages50to54', models.IntegerField(default=0)),
                ('ages55to59', models.IntegerField(default=0)),
                ('ages60to64', models.IntegerField(default=0)),
                ('ages65to69', models.IntegerField(default=0)),
                ('ages70to74', models.IntegerField(default=0)),
                ('ages75to79', models.IntegerField(default=0)),
                ('ages80to84', models.IntegerField(default=0)),
                ('ages85plus', models.IntegerField(default=0)),
                ('practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='catalog.gppractices')),
            ],
            options={
                'ordering': ['practice', 'sex'],
                'unique_together': {('practice', 'sex')},
            },
        ),
    ]
